name: Issue Metrics

on:
  schedule:
    - cron: "0 7 * * 1-5"   # 07:00 UTC on weekdays
  workflow_dispatch:

# Make sure the workflow can create an issue for the report
permissions:
  contents: read
  issues: write
  pull-requests: read

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Set time window (last 7 days)
        shell: bash
        run: |
          since="$(date -u -d '7 days ago' +%Y-%m-%d)"
          echo "SINCE=${since}" >> $GITHUB_ENV

      - name: Run issue-metrics
        uses: github/issue-metrics@v3
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # GitHub search query for the report (adjust as you like)
          # Examples to try:
          #   'repo:${{ github.repository }} is:issue created:>=${{ env.SINCE }}'
          #   'repo:${{ github.repository }} is:issue updated:>=${{ env.SINCE }}'
          SEARCH_QUERY: 'repo:${{ github.repository }} is:issue created:>=${{ env.SINCE }}'

      - name: Publish report as issue
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: "Issue metrics report (${% raw %}{{ env.SINCE }}{% endraw %} → today)"
          token: ${{ secrets.GITHUB_TOKEN }}
          content-filepath: ./issue_metrics.md
          labels: "team-metrics"
